#!/bin/bash

# settings
rootpth="$HOME/hd"
pathout="$rootpth/plots"
rawfile="$rootpth/data/data"
langpck="$rootpth/data/langpack"
datapnt=$(wc -l < $rawfile)

# language of plot labels and titles
# shellcheck source=/home/mumrik/hd/data/langpack
. "$langpck" # import labels and titles

gnuplot -p <<EOF
set style line 100 lt 1 lc rgb "black" lw 1
set style line 101 lt 0.5 lc rgb "gray" lw 1
set grid mxtics xtics mytics ytics ls 100, ls 101
set tics font ",9"
set ylabel "${l4[${lng}]}"
set xlabel "${l3[${lng}]}"
set title "bgl and weight over $datapnt data points" font ",12"
set terminal png enhanced background rgb '#F0F7D4'
set mytics 2
set mxtics 5
set pointsize
set nokey
set xrange [125:95] reverse
set output "$pathout/bglandweight.png"
set style circle radius 0.15
plot "$rawfile" u 2:3 with circles lc rgb "green" fs solid 1.0 border lt -1, \
     '' u 2:(\$3>6.1?\$3:1/0) w circles lc rgb "red" fs solid 1.0 border lt -1
EOF

