#!/bin/bash

rootpth="$HOME/hd"
datafle="$rootpth/data/bp"
tempfle=$(mktemp /tmp/bp.XXXXXX)
langpck="$rootpth/data/langpack"

# language of plot labels and titles
# shellcheck source=/home/mumrik/hd/data/langpack
. "$langpck" # import labels and titles

trap 'rm -f -- "$tempfle"' EXIT
tail -n 10 "$datafle" >> "$tempfle"

gnuplot -p << EOF
set terminal png enhanced background rgb '#F0F7D4' size 600,400
set output "$HOME/hd/plots/bp.png"
set style line 100 lt 1 lc rgb "black" lw 1
set style line 101 lt 0.5 lc rgb "gray" lw 1
set grid noxtics mytics ytics ls 100, ls 101
set title "${l11[${lng}]}" font ",12"
set key reverse spacing 0.85 box font ',9'
set tics font ",9"
set xtics rotate nomirror 
set mytics 2
set ytics 10
set yrange [50:160]
set style histogram clustered gap 1
set style data histograms 
set boxwidth 0.5 relative
set style fill solid 0.50 border -1
set fit quiet
set fit logfile '/dev/null'
f(x) = mean_s
fit f(x) "$tempfle" u 1:2 via mean_s
f(x) = mean_d
fit f(x) "$tempfle" u 1:3 via mean_d
f(x) = mean_h
fit f(x) "$tempfle" u 1:4 via mean_h
plot "$tempfle" u 2:xticlabels(1) lc rgb '#9ACD32' title "${l12[${lng}]}", \
"" u 3 lc rgb 'yellow' title "${l13[${lng}]}", \
"" u 4 lc rgb 'orange' title "${l14[${lng}]}", \
mean_s w l lc rgb '#9ACD32' notitle, \
mean_d w l lc 'yellow' notitle, \
mean_h w l lc 'orange' notitle
EOF
