#!/bin/bash

FORMAT='+%Y%m%d%H%M'
FILE="$HOME/hd/data/$1sleep"

rangeTo=$( < "$FILE" wc -l )
(( rangeFrom = rangeTo - 30 ))

gnuplot -p << EOF
set terminal png enhanced background rgb '#F0F7D4' size 800,600
set output "$HOME/hd/plots/$1sleep.png"
set grid
set title "hours slept $1" font ",12"
set key invert reverse spacing 0.85 box font ',9' autotitle columnhead
set tics font ",9"
set xtics rotate nomirror
set mytics 4
set ytics 0,60
set y2tics 0,60
set autoscale y
set style histogram rowstacked
set style data histograms
set style line 100 lt 1 lc rgb "black" lw 1
set style line 101 lt 0.5 lc rgb "gray" lw 1
set grid noxtics mytics ytics ls 100, ls 101
set boxwidth 0.50 relative
set style fill solid 0.50 border -1

plot "$FILE" using 3:xticlabels(1) lc rgb 'yellow', "" using 2 lc rgb 'green'
EOF

