#!/bin/bash

filein=$HOME/hd/data/data
fileout=$HOME/hd/data/processed
wtrend=''
mtrend=''

[ -f "$fileout" ] && mv "$fileout" "$fileout.bck"
printf '#Date Weight Trend BMI BSL Trend\n' > "$fileout"
while read -r date weight mmoll
do
  if [ -z "$wtrend" ] 
  then
    wtrend=$weight
  else
    wtrend=$(echo "scale=3;$wtrend+0.1*($weight-$wtrend)" | bc)
  fi
  if [ -z "$mtrend" ] 
  then
    mtrend=$mmoll
  else
    mtrend=$(echo "scale=3;$mtrend+0.1*($mmoll-$mtrend)" | bc)
  fi
  bmi=$(echo "scale=3;$wtrend/(1.75^2)" | bc)
  printf '%s %.2f %.2f %.2f %.2f %.2f\n' "$date" "$weight" "$wtrend" "$bmi" "$mmoll" "$mtrend" >> "$fileout"
done < "$filein"
