#!/bin/bash

FORMAT='+%Y-%m-%d'
FILE="$HOME/hd/data/processed"
DIETFILE="$HOME/hd/data/diet"

if [ "$#" -eq 0 ]; then
  rangeFrom=$( date -d "-31 days" $FORMAT )
  rangeTo=$( date -d "+1 day" $FORMAT )
elif [ "$#" -eq 2 ]; then
  rangeFrom=$( date -d "$1 - 1 day" $FORMAT )
  rangeTo=$( date -d "$2 + 1 day" $FORMAT )
else
  echo "Usage: $0 [FROM_DATE TO_DATE]"
  exit -1
fi

if [ -e "$DIETFILE" ]; then
#  PLOT_DIET="\"$DIETFILE\" using 1:2 with lines dashtype 2 linecolor \"dark-yellow\" linewidth 1.5 notitle"
  PLOT_DIET="\"$DIETFILE\" using 1:2 with lines lt 0 lw 2 lc rgb '#5F9EA0' title 'diet plan'"
fi

gnuplot -p << EOF
set xdata time
set timefmt "%Y-%m-%d"
set format x "%b"
set xtics "2018-08-01",2592000,"2019-05-30" #rotate
unset mxtics
set ytics 1
set tics font ",9"
set grid
set xrange ["$rangeFrom":"$rangeTo"]
set autoscale y
set autoscale x
set terminal png truecolor enhanced background rgb '#F0F7D4' size 800,600
set output "$HOME/hd/plots/progress.png"
set key reverse spacing 0.85 box font ',9'
set x2label 'overall weight loss porgress' font ',11'

set arrow from graph 0,first 92 to graph 1, first 92 nohead lt 0 lw 2 lc rgb '#FC600A' front

plot 92 with filledcurves y1=200 fs transparent solid 0.25 lc rgb '#FF4500' title "obese", \
92 with filledcurves y1=77 fs transparent solid 0.25 lc rgb '#FFA500' title "overweight", \
"$FILE" using 1:3 with lines linecolor rgb '#2E8B57' linewidth 1.5 title "trend", \
$PLOT_DIET
EOF
