#!/bin/bash

datefmt='+%Y%m'
rootpth="$HOME/hd"
langpck="$rootpth/data/langpack"

function die() {
  echo "$@" >&2
  exit 1
}

# language of plot labels and titles
# shellcheck source=/home/mumrik/hd/data/langpack
. "$langpck" # import labels and titles

if [ "$#" -eq 0 ]; then
  datafle="$rootpth/data/$(date $datefmt)"
  outfile="$rootpth/plots/$(date $datefmt).png"
elif [ "$#" -eq 1 ]; then
  datafle="$rootpth/data/$1"
  outfile="$rootpth/plots/$1.png"
else
  die "Usage: $0 [YYYYDD]"
fi
[ -f "$datafle" ] || die "Data file $datafle does not exist!"

means=$( awk '{x+=$2; v += ($2 > 0) ? 1 : 0; next} END{print x/v}' "$datafle" )
meanw=$( awk '{x+=$3; v += ($3 > 0) ? 1 : 0; next} END{print x/v}' "$datafle" )
meana=$( awk '{x+=$6; v += ($6 > 0) ? 1 : 0; next} END{print x/v}' "$datafle" )

gnuplot -p <<EOF
stats '$datafle' using 2:6 nooutput
set terminal png enhanced background rgb '#F0F7D4' size 1200,600
set output "$outfile"
set style line 100 lt 1 lc rgb "black" lw 1
set style line 101 lt 0.5 lc rgb "gray" lw 1
set grid noxtics mytics ytics ls 100, ls 101
set key invert reverse spacing 0.85 box font ',9' autotitle columnhead
set tics font ",9"
set xtics rotate nomirror
set mytics 4
set ytics 0,60
set y2tics 0,60
set autoscale y
set style histogram rowstacked
set style data histograms
set boxwidth 0.5 relative
set style fill solid 0.50 border -1
set multiplot layout 1,2 title "$1" font ",12"
set tmargin 1.5
set title "${l7[${lng}]}" font ",12"
set arrow from graph 0,first "$means" to graph 1, first $means nohead lt 0 lc rgb 'red' front
set arrow from graph 0,first "$meanw" to graph 1, first $meanw nohead lt 0 lc rgb 'orange' front
plot "$datafle" using 3:xticlabels(1) lc rgb 'yellow' title "${l10[${lng}]}", \
"" using 2 lc rgb 'green' title "${l9[${lng}]}"
set title "${l8[${lng}]}" font ",12"
set ytics 1000
set y2tics 1000
set mytics 2.5
unset arrow
set arrow from graph 0,first "$meana" to graph 1, first $meana nohead lt 0 lc rgb 'red' front
plot "$datafle" using 6:xticlabels(1) lc rgb 'green' title "${l8[${lng}]}"
EOF
