#!/bin/bash

# settings
rootpth="$HOME/P/projects/hd"
datafle="$rootpth/data/processed"
dietfle="$rootpth/data/diet"
pathout="$rootpth/plots"
rawfile="$rootpth/data/data"
langpck="$rootpth/data/langpack"
datefmt='+%Y-%m-%d'
wtrend=''
mtrend=''

# language of plot labels and titles
# shellcheck source=/home/rubin/P/projects/hd/data/langpack
. "$langpck" # import labels and titles

# process raw data generate processed data file
[ -f "$darafle" ] && mv "$datafle" "$datafle.bck"
printf '#Date Weight Trend BMI BSL Trend\n' >"$datafle"
while read -r date weight mmoll; do
  if [ -z "$wtrend" ]; then
    wtrend=$weight
  else
    wtrend=$(echo "scale=3;$wtrend+0.1*($weight-$wtrend)" | bc)
  fi
  if [ -z "$mtrend" ]; then
    mtrend=$mmoll
  else
    mtrend=$(echo "scale=3;$mtrend+0.1*($mmoll-$mtrend)" | bc)
  fi
  bmi=$(echo "scale=3;$wtrend/(1.75^2)" | bc)
  printf '%s %.2f %.2f %.2f %.2f %.2f\n' \
    "$date" "$weight" "$wtrend" "$bmi" "$mmoll" "$mtrend" >>"$datafle"
done <"$rawfile"

# plots
if [ "$#" -eq 0 ]; then
  datefr=$(date -d "-31 days" $datefmt)
  dateto=$(date -d "+1 day" $datefmt)
  combfl="dataplot.png"
  wghtfl="weight.png"
elif [ "$#" -eq 2 ]; then
  datefr=$(date -d "$1 - 1 day" $datefmt)
  dateto=$(date -d "$2 + 1 day" $datefmt)
  combfl="wlbs-$datefr-$dateto.png"
  wghtfl="wl-$datefr-$dateto.png"
else
  echo "Usage: $0 [FROM_DATE TO_DATE]"
  exit 1
fi
if [ -e "$dietfle" ]; then
  dietplt="\"$dietfle\" using 1:2 with lines lt 0 lw 2 lc rgb '#5F9EA0'\
    title \"${l0[${lng}]}\""
fi

gnuplot -p <<EOF
set timefmt "%Y-%m-%d"
set key samplen -1 font ',12' textcolor variable
set tics font ",9"
set xdata time
set format x "%m-%d"
set xtics 86400 rotate nomirror # 1 day
unset mxtics
set xrange ["$datefr":"$dateto"]
set ytics 1 nomirror
set y2tics 1
set autoscale y
set autoscale y2
set xlabel "date" font ",12"
set ylabel "kg" font ",12"
set y2label "mmol/L" font ",12"
# plot weight/blood sugar
set terminal png truecolor enhanced background rgb '#F0F7D4' size 640,480
set output "$pathout/weightbsl.png"
plot "$datafle" using 1:3 with lines linecolor rgb '#2E8B57' linewidth 2 title "тегло", \
"$datafle" using 1:6 axes x1y2 with lines linecolor rgb '#FC600A' linewidth 2 title "глюкоза в кръвта"
EOF
