#!/bin/bash

# settings
rootpth="$HOME/P/projects/hd"
datafle="$rootpth/data/processed"
dietfle="$rootpth/data/diet"
pathout="$rootpth/plots"
rawfile="$rootpth/data/data"
langpck="$rootpth/data/langpack"
datefmt='+%Y-%m-%d'
wtrend=''
mtrend=''

# language of plot labels and titles
# shellcheck source=/home/rubin/P/projects/hd/data/langpack
. "$langpck" # import labels and titles

# process raw data generate processed data file
[ -f "$darafle" ] && mv "$datafle" "$datafle.bck"
printf '#Date Weight Trend BMI BSL Trend\n' >"$datafle"
while read -r date weight mmoll; do
  if [ -z "$wtrend" ]; then
    wtrend=$weight
  else
    wtrend=$(echo "scale=3;$wtrend+0.1*($weight-$wtrend)" | bc)
  fi
  if [ -z "$mtrend" ]; then
    mtrend=$mmoll
  else
    mtrend=$(echo "scale=3;$mtrend+0.1*($mmoll-$mtrend)" | bc)
  fi
  bmi=$(echo "scale=3;$wtrend/(1.75^2)" | bc)
  printf '%s %.2f %.2f %.2f %.2f %.2f\n' \
    "$date" "$weight" "$wtrend" "$bmi" "$mmoll" "$mtrend" >>"$datafle"
done <"$rawfile"

# plots
if [ "$#" -eq 0 ]; then
  datefr=$(date -d "-31 days" $datefmt)
  dateto=$(date -d "+1 day" $datefmt)
  combfl="dataplot.png"
  wghtfl="weight.png"
elif [ "$#" -eq 2 ]; then
  datefr=$(date -d "$1 - 1 day" $datefmt)
  dateto=$(date -d "$2 + 1 day" $datefmt)
  combfl="wlbs-$datefr-$dateto.png"
  wghtfl="wl-$datefr-$dateto.png"
else
  echo "Usage: $0 [FROM_DATE TO_DATE]"
  exit 1
fi
if [ -e "$dietfle" ]; then
  dietplt="\"$dietfle\" using 1:2 with lines lt 0 lw 2 lc rgb '#5F9EA0'\
    title \"${l0[${lng}]}\""
fi

gnuplot -p <<EOF
set timefmt "%Y-%m-%d"
set grid
set key reverse spacing 0.85 box font ',9'
set tics font ",9"
set xdata time
set format x "%m-%d"
set xtics 86400 rotate # 1 day
unset mxtics
set xrange ["$datefr":"$dateto"]
set ytics 0.5
set autoscale y

# plot weight and bsl
set terminal png truecolor enhanced background rgb '#F0F7D4' size 1200,600
set output "$pathout/$combfl"
set multiplot layout 1,2 title "$datefr - $dateto" font ",12"
set tmargin 1.5 
set x2label "${l3[${lng}]}" font ',11'
plot "$datafle" using 1:2 with points linecolor rgb '#FC600A' pt 6 title "${l1[${lng}]}", \
"$datafle" using 1:3 with lines linecolor rgb '#FC600A' linewidth 1.5 title "${l2[${lng}]}", \
"$datafle" using 1:3:(0):(\$2-\$3) with vectors nohead linecolor rgb '#B2D732' linewidth 1.5 notitle, \
$dietplt
set arrow from graph 0,first 6.1 to graph 1, first 6.1 nohead lt 0 lw 2 lc rgb '#5F9EA0' front
#set arrow from graph 0,first 4.1 to graph 1, first 4.1 nohead lt 0 lw 2 lc rgb '#5F9EA0' front
set x2label "${l4[${lng}]}" font ',11'
plot 6.1 with filledcurves y1=4.1 fs transparent solid 0.15 lc rgb '#AFEEEE' notitle, \
"$datafle" using 1:5 with points linecolor rgb '#FC600A' pt 6 title "${l1[${lng}]}", \
"$datafle" using 1:6 with lines linecolor rgb '#FC600A' linewidth 1.5 title "${l2[${lng}]}", \
"$datafle" using 1:6:(0):(\$5-\$6) with vectors nohead linecolor rgb '#B2D732' linewidth 1.5 notitle

# plot weight
unset multiplot
set terminal png truecolor enhanced background rgb '#F0F7D4' size 800,600
set output "$pathout/$wghtfl"
set x2label '$datefr - $dateto' font ',11'
plot "$datafle" using 1:2 with points linecolor rgb '#FC600A' pt 6 title "${l1[${lng}]}", \
"$datafle" using 1:3 with lines linecolor rgb '#FC600A' linewidth 1.5 title "${l2[${lng}]}", \
"$datafle" using 1:3:(0):(\$2-\$3) with vectors nohead linecolor rgb '#B2D732' linewidth 1.5 notitle, \
$dietplt

# plot overall progress
set format x "%b"
set xtics "2019-05-01",2592000,"2019-10-08" #rotate
set ytics 1
set autoscale y
set autoscale x
set output "$pathout/progress.png"
set x2label "${l3[${lng}]}" font ',11'
set arrow from graph 0,first 92 to graph 1, first 92 nohead lt 0 lw 2 lc rgb '#FC600A' front
plot 92 with filledcurves y1=200 fs transparent solid 0.25 lc rgb '#FF4500' title "${l5[${lng}]}", \
92 with filledcurves y1=77 fs transparent solid 0.25 lc rgb '#FFA500' title "${l6[${lng}]}", \
"$datafle" using 1:3 with lines linecolor rgb '#FA8072' linewidth 1.5 title "${l2[${lng}]}", \
"$datafle" using 1:2 with lines linecolor rgb '#2E8B57' linewidth 1.5 title "${l1[${lng}]}", \
$dietplt

# plot overall progress
unset arrow
set style line 100 lt 1 lc rgb "black" lw 1
set style line 101 lt 0.5 lc rgb "gray" lw 1
set grid noxtics mytics ytics ls 100, ls 101
set format x "%b"
set xtics "2019-05-03",2592000,"2019-10-08" #rotate
set ytics 1
set mytics 5
set autoscale y
set autoscale x
set output "$pathout/blsprogress.png"
set x2label "${l4[${lng}]}" font ',11'
set style fill transparent solid 0.25 noborder
plot 6.1 with filledcurves y1=4.1 fs lc rgb '#B3FF66' notitle, \
6.1 with filledcurves y1=20 fs lc rgb '#AFEEEE' notitle, \
3 with filledcurves y1=4.1 fs lc rgb '#FC600A' notitle, \
"$datafle" using 1:6 with lines linecolor rgb '#FC600A' linewidth 1.5 title "${l2[${lng}]}", \
"$datafle" using 1:5 with points linecolor rgb '#FC600A' pt 6 ps 0.5 title "${l1[${lng}]}", \
"$datafle" using 1:6:(0):(\$5-\$6) with vectors nohead linecolor rgb '#B2D732' linewidth 1.5 notitle
EOF
