#!/bin/bash

FORMAT='+%Y-%m-%d'
FILE="$HOME/hd/data/wprocessed"
DIETFILE="$HOME/hd/data/diet"

if [ "$#" -eq 0 ]; then
    rangeFrom=`date -d "-31 days" $FORMAT`
    rangeTo=`date -d "+2 day" $FORMAT`
elif [ "$#" -eq 2 ]; then
    rangeFrom=`date -d "$1 - 1 day" $FORMAT`
    rangeTo=`date -d "$2 + 1 day" $FORMAT`
else
    echo "Usage: $0 [FROM_DATE TO_DATE]"
    exit -1
fi

if [ -e "$DIETFILE" ]; then
#  PLOT_DIET="\"$DIETFILE\" using 1:2 with lines dashtype 2 linecolor \"dark-yellow\" linewidth 1.5 notitle"
  PLOT_DIET="\"$DIETFILE\" using 1:2 with lines lt 0 lw 2 lc rgb '#5F9EA0' title 'diet plan'"
fi

gnuplot -p << EOF
set xdata time
set timefmt "%Y-%m-%d"
set format x "%m-%d"
set xtics 86400 rotate # 1 day
set ytics 0.5
set y2tics 0.5
unset mxtics
set grid
#set xrange ["$rangeFrom":"$rangeTo"]
set xrange [(system("date -d 'now' +%s")-2592000):(system("date -d 'now' +%s"))]
set autoscale y
#set terminal x11 size 800,600 background "white"
set terminal png enhanced background rgb '#F0F7D4'
set output "$HOME/hd/plots/weight.png"
set xlabel "date"
set ylabel "weight"
set key reverse spacing 0.85 box

#plot "$FILE" using 1:3 with lines linecolor rgb '#FC600A' linewidth 1.5 title "trend", \

plot "$FILE" using 1:2 with points linecolor rgb '#B2D732' pointtype 6 title "weight", \
"$FILE" using 1:3 with lines linecolor rgb '#FC600A' linewidth 1.5 title "trend", \
"$FILE" using 1:3:(0):(\$2-\$3) with vectors linecolor rgb '#B2D732' linewidth 1.5 notitle, \
$PLOT_DIET
EOF
